interface OutputJSBase {};

[JSImplementation="OutputJSBase"]
interface OutputJS {
	void OutputJS();
	void appendCallback([Const] DOMString s, unsigned long n);
};

[Prefix="open_vcdiff::"]
interface VCDiffStreamingDecoder {
	void VCDiffStreamingDecoder();
	void StartDecoding([Const] DOMString dictionary_ptr, unsigned long dictionary_size);
	boolean DecodeChunkToInterface([Const] DOMString data, unsigned long len, OutputJS output);
	boolean FinishDecoding();
};
