interface OutputString {
	void OutputString();
	[Const] DOMString data();
	unsigned long size();
};

[Prefix="open_vcdiff::"]
interface VCDiffStreamingDecoder {
	void VCDiffStreamingDecoder();
	void StartDecoding([Const] DOMString dictionary_ptr, unsigned long dictionary_size);
	boolean DecodeChunkToInterface([Const] DOMString data, unsigned long len, OutputString output);
	boolean FinishDecoding();
};
